import { test } from "node:test";
import assert from "node:assert/strict";
import { defaults, decode } from "../src/save.ts";
import { Game } from "../src/state.ts";
import { TREES } from "../src/skill-trees.ts";
import { UPGRADES } from "../src/config.ts";
test("fresh progression gates Delve, currencies, Courage root, and Legacy", () => {
  const g = new Game(defaults());
  g.save.tower.shards = 100;
  g.save.delve.essence = 100;
  g.switchMode("delve");
  assert.equal(g.mode, "tower");
  assert.equal(g.buy("auto"), false);
  assert.equal(g.buy("delve"), false);
  for (const id of ["shardHp", "shardAttack", "shardDefense", "delve"] as const) assert.ok(g.buy(id));
  assert.equal(g.save.delve.essence, 100);
  g.switchMode("delve");
  assert.equal(g.mode, "delve");
  assert.equal(g.buy("hp"), false);
  assert.ok(g.buy("auto"));
  assert.equal(g.save.delve.essence, 97);
  assert.ok(g.buy("hp"));
  assert.equal(g.buy("quality"), false);
  const restored = new Game(decode(JSON.stringify(g.save)));
  assert.equal(restored.save.upgrades.auto, 1);
  restored.switchMode("delve");
  assert.equal(restored.mode, "delve");
  assert.equal(TREES[1].nodes[0].id, "auto");
  assert.ok(TREES[0].nodes.every(n => UPGRADES.find(u => u.id === n.id)!.currency === "shards"));
  assert.deepEqual(TREES.map(tree => tree.id), ["inspiration", "courage", "legacy", "wisdom", "renown"]);
  assert.ok(TREES.slice(3).every(tree => tree.nodes.length >= 3));
});
test("older saves retain earned access without unlocking fresh saves", () => {
  const old: any = defaults();
  delete old.upgrades.delve;
  delete old.upgrades.legacy;
  assert.equal(decode(JSON.stringify(old)).upgrades.delve, 0);
  old.upgrades.quality = 2;
  const saved = decode(JSON.stringify(old));
  assert.equal(saved.upgrades.delve, 1);
  assert.equal(saved.upgrades.legacy, 1);
  assert.equal(saved.upgrades.quality, 2);
});
